#############
### build ###
#############

# base image
FROM node:12.18.1-alpine as build

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json package-lock.json ./
RUN npm ci

# add app
COPY . /app

# generate build
RUN npm run build -- --prod --output-path=dist

############
### prod ###
############

# base image
FROM nginx:1.17.6-alpine

# copy artifact build from the 'build environment'
COPY --from=build /app/dist /usr/share/nginx/html

# copy nginx configuration
COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

# expose port 80
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]
