import { User } from '../../models/user';

export const users: User[] = [
  {
    id: 1,
    name: 'Victor Wolmeister',
    country: 'Canada',
    email: 'victor@gmail.com',
    phone: '(51) 99999-9876',
    plan: 'Ultra HD',
    password: 'test',
  },
  {
    id: 2,
    name: 'Matheus Michels',
    country: 'Brazil',
    email: 'mm@gmail.com',
    phone: '(51) 99999-1234',
    plan: 'Standard HD',
    password: '1234',
  },
  {
    id: 3,
    name: 'Geraldo',
    country: 'Poland',
    email: 'geraldo@gmail.com',
    phone: '(51) 99999-6789',
    plan: 'Ultra HD',
    password: 'rivia',
  },
  {
    id: 4,
    name: 'Trixie',
    country: 'Canada',
    email: 'trixie@gmail.com',
    phone: '(51) 99999-9876',
    plan: 'Ultra HD',
    password: 'test',
  },
  {
    id: 5,
    name: 'Slade Wilson',
    country: 'Brazil',
    email: 'slade@gmail.com',
    phone: '(51) 99999-1234',
    plan: 'Standard HD',
    password: '1234',
  },
  {
    id: 6,
    name: 'Triss',
    country: 'Poland',
    email: 'triss@gmail.com',
    phone: '(51) 99999-6789',
    plan: 'Ultra HD',
    password: 'password',
  },
];
